source-file ~/.config/tmux/theme.conf

# Change prefix
unbind C-b
set -g prefix C-x

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Enable mouse
set -g mouse on

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Change split keys and make new splits/windows open in current path
unbind '"'
unbind %
bind c new-window -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind = split-window -h -c "#{pane_current_path}"

# Kill current pane or window
unbind q
bind-key q run-shell "\
  if [ \$(tmux list-panes | wc -l) -gt 1 ]; then \
    tmux kill-pane; \
  else \
    tmux kill-window; \
  fi"

# Next window
bind C-x next-window

# Shortcut to reload tmux config
bind r source-file ~/.config/tmux/tmux.conf
